use_frameworks!

platform :ios, '12.0'

target 'Rio_Example' do
  pod 'Rio', :path => '../'

  target 'Rio_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end