use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'Rio_Example' do
  pod 'Rio', :path => '../'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end