name: CI
on:
  push:
    tags:
    - '*'
    
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to CocoaPods 
        run: |
          pod trunk push --allow-warnings Rio.podspec 
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
